name: Update Secrets

on:
  push:
    branches:
      - master

jobs:
  update_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run update_secrets_script.sh
        run: sh update_secrets_script.sh
