name: Update Secrets

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  update_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run update_secrets_script.sh
        run: |
          sudo chmod +x ./.github/scripts/update_secrets_script.sh
          ./.github/scripts/update_secrets_script.sh

      - name: Add updated secrets file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add api/_secrets.json
          git commit -m "update secrets file 🤖"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
